# Generated by Django 2.1 on 2018-08-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DadosEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cargo')),
            ],
        ),
    ]
