# Generated by Django 2.1 on 2018-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosempresa',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
