# Generated by Django 2.1 on 2018-08-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DadosEmpresa',
            new_name='Empresa',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='texto',
            new_name='resposta',
        ),
    ]
