# Generated by Django 2.2.7 on 2019-11-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180819_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data_resposta',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='resposta',
            field=models.TextField(blank=True),
        ),
    ]
